services:
  # File Browser Application (API + Web Frontend)
  filebrowser:
    build:
      context: .
      dockerfile: FileBrowser.Api/Dockerfile
    container_name: filebrowser
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FileBrowser__HomeDirectory=/app/files
    volumes:
      - filebrowser-data:/app/files
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  filebrowser-data:
    driver: local
